### PR TITLE
Fixed parsing of device discover response failing on uppercase keys.

### PR DESCRIPTION
**Pull request by SchizoDuckie**
So, it turns out my tv sends LOCATION instead of Location. I tuned the code to handle this gracefully :)

### CODE REVIEW

**Comment by SchizoDuckie** [comment]
Thanks for merging! Could you tag a release so I can target it with NPM?

**Comment by manrueda** [comment]
Yes, i will bump the version in a few hours... i'm not at home now haha

**Comment by SchizoDuckie** [comment]
No problem man :+1:  enjoy the weekend!

**Comment by manrueda** [comment]
Done! you should see the new version

**Comment by SchizoDuckie** [comment]
Awesome thanks! i'm using [here](http://github.com/acidhax/streaming-media-encoder/) in the chromecast example :) keep an eye on that repo for cool stuff coming!

**Pull request merged**
